-- INSERT INTO users (email, password, nickname, role, grade, point, create_at, update_at)
-- VALUES ('user1@example.com', '$2a$10$92EXtYPmTZcYUN7I1kUO1e8cEcpkDf4J8KXDRYjPupSn5RUyn0WPu', 'user1', 'ROLE_USER', 'grade1', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
--
-- INSERT INTO users (email, password, nickname, role, grade, point, create_at, update_at)
-- VALUES ('user2@example.com', '$2a$10$92EXtYPmTZcYUN7I1kUO1e8cEcpkDf4J8KXDRYjPupSn5RUyn0WPu', 'user2', 'ROLE_USER', 'grade2', 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
--
-- INSERT INTO users (email, password, nickname, role, grade, point, create_at, update_at)
-- VALUES ('admin@example.com', '$2a$10$92EXtYPmTZcYUN7I1kUO1e8cEcpkDf4J8KXDRYjPupSn5RUyn0WPu', 'admin', 'ROLE_ADMIN', 'grade3', 120, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);